// Generated by CoffeeScript 1.9.2
(function() {
  var bodyParser, cookieParser, express, init, server;

  express = require('express');

  cookieParser = require('cookie-parser');

  bodyParser = require('body-parser');

  server = express();

  server.use(bodyParser.json({}));

  server.use(bodyParser.urlencoded({
    extended: false
  }));

  server.use(cookieParser());

  init = require('./init');

  init(server, function(err) {
    var port;
    if (err) {
      console.log(err);
      console.log(err.stack);
      return;
    }
    port = 10090;
    return server.listen(port, function() {
      return console.log('listening at %s', port);
    });
  });

}).call(this);
