// Generated by CoffeeScript 1.9.2
(function() {
  var api, request, utils;

  request = require('request');

  utils = require('../utils');

  api = {
    first: "/articles/first",
    next: function(id) {
      return "/articles/next/" + id;
    },
    article: function(id) {
      return "http://127.0.0.1:10080/api/articles/" + id;
    }
  };

  module.exports = {
    queryById: function(req, res, next) {
      var articleId;
      articleId = req.params.articleId;
      return request.get(api.article(articleId), function(err, result) {
        if (err) {
          return next(err);
        }
        return utils.parseJson(result.body, function(err, body) {
          if (err) {
            return next(err);
          }
          return res.render('article', body);
        });
      });
    }
  };

}).call(this);
