// Generated by CoffeeScript 1.9.2
(function() {
  var api, request;

  request = require('request');

  api = {
    first: "/articles/first",
    next: function(id) {
      return "/articles/next/" + id;
    }
  };

  module.exports = {
    list: function(req, res, next) {}
  };

}).call(this);
