// Generated by CoffeeScript 1.9.2
(function() {
  var ctrls;

  ctrls = require('./ctrls');

  module.exports = function(server) {
    return server.get('/articles/:articleId', ctrls.article.queryById);
  };

}).call(this);
