// Generated by CoffeeScript 1.9.2
(function() {
  var bodyParser, cookieParser, express, init, path, route, server;

  path = require('path');

  express = require('express');

  cookieParser = require('cookie-parser');

  bodyParser = require('body-parser');

  server = express();

  server.use(bodyParser.json({}));

  server.use(bodyParser.urlencoded({
    extended: false
  }));

  server.use(cookieParser());

  server.set('views', path.join(__dirname, '../views'));

  server.set('view engine', 'ejs');

  server.use(express["static"](path.join(__dirname, '../public')));

  route = require('./route');

  route(server);

  init = require('./init');

  init(server, function(err) {
    var port;
    if (err) {
      console.log(err);
      console.log(err.stack);
      return;
    }
    port = 10100;
    return server.listen(port, function() {
      return console.log('listening at %s', port);
    });
  });

}).call(this);
