// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = {
    parseJson: function(string, callback) {
      var err, result;
      try {
        result = JSON.parse(string);
        return callback(null, result);
      } catch (_error) {
        err = _error;
        return callback(err);
      }
    }
  };

}).call(this);
